import pandas as pd
import numpy as np
import plotly.express as px


def execute_code(code, df):

    # Block unsafe operations
    forbidden = [
        "import ",
        "os.",
        "sys.",
        "subprocess",
        "open(",
        "__",
        "eval(",
        "exec(",
        "write(",
        "read(",
        "shutil",
        "pathlib",
        "socket",
        "requests",
        "http",
    ]

    for word in forbidden:
        if word in code:
            return f"Unsafe code detected: {word}"

    # Provide pandas and numpy in the execution scope
    # so AI-generated code like df.groupby().agg() works correctly
    global_vars = {
        "pd": pd,
        "np": np,
        "px": px,
    }

    local_vars = {"df": df}

    try:

        # Execute generated code
        exec(code, global_vars, local_vars)

        # Extract result safely
        result = local_vars.get("result", None)
        charts = local_vars.get("charts", [])

        if result is None:
            return "No result generated by the analysis code."

        if charts:
            return result, charts
            
        return result

    except Exception as e:
        return f"Code execution error: {str(e)}"